version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14  # Use the Node.js Docker image

jobs:
  # Job to install dependencies and test the backend
  test-backend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd BACKEND
            npm install
      - run:
          name: Run Backend Tests
          command: |
            cd BACKEND
            npm test  # Assuming you have tests set up

  # Job to install dependencies and test the frontend
  test-frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: |
            cd FRONTEND/client
            npm install
      - run:
          name: Run Frontend Tests
          command: |
            cd FRONTEND/client
            npm test  # Assuming you have tests set up
      - run:
          name: Build Frontend
          command: |
            cd FRONTEND/client
            npm run build

# Define the workflow
workflows:
  version: 2
  test-and-build:
    jobs:
      - test-backend
      - test-frontend
