version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14  # Use the Node.js Docker image

jobs:
  # Job to install dependencies and test the backend
  test-backend:
    executor: node-executor
    steps:git 
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd BACKEND
            npm install
      - run:
          name: Run Backend Tests
          command: |
            cd BACKEND
            npm test  # Assuming you have tests set up

  # Job to install dependencies and test the frontend
  test-frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: |
            cd FRONTEND/client
            npm install
      - run:
          name: Run Frontend Tests
          command: |
            cd FRONTEND/client
            npm test  # Assuming you have tests set up
      - run:
          name: Build Frontend
          command: |
            cd FRONTEND/client
            npm run build

  # Job to run SonarCloud analysis
  sonarcloud-analysis:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Use SonarScanner Docker image
    steps:
      - checkout
      - run:
          name: SonarCloud Analysis
          command: |
            sonar-scanner \
              -Dsonar.organization="joshuaashley" \  # Organization key
              -Dsonar.projectKey="EasyBank" \        # Project key
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login=$SONAR_TOKEN

# Define the workflow
workflows:
  version: 2
  test-and-build:
    jobs:
      - test-backend
      - test-frontend
      - sonarcloud-analysis
