version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  test-backend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd BACKEND
            npm install
      - run:
          name: Run Backend Tests
          command: |
            cd BACKEND
            npm test

  test-frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: |
            cd FRONTEND/client
            npm install
      - run:
          name: Run Frontend Tests
          command: |
            cd FRONTEND/client
            npm test
      - run:
          name: Build Frontend
          command: |
            cd FRONTEND/client
            npm run build

  sonarcloud:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            npm install sonar-scanner --save-dev
      - run:
          name: Run SonarCloud Analysis
          command: |
            cd BACKEND
            npx sonar-scanner \
              -Dsonar.projectKey="EasyBank" \
              -Dsonar.sources=. \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.branch.name="${CIRCLE_BRANCH}"

workflows:
  version: 2
  test-and-build:
    jobs:
      - test-backend
      - test-frontend
      - sonarcloud
